apiVersion: v1
kind: Secret
metadata:
  name: harbor-db-password
  namespace: harbor
type: Opaque
stringData:
  password: [Non-encoded value]

---

apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry
  namespace: default
  annotations:
    kubed.appscode.com/sync: ""
type: Opaque
stringData:
  password: [Non-encoded value]
