{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app.name }}-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      successfulJobsHistoryLimit: 1
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets.name }}
          containers:
            - name: "{{ .Values.app.name }}"
              image: "{{ .Values.stressTester.image.repository }}:{{ default (include "app-demo.defaultTag" .) .Values.global.image.tag }}"
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: {{ .Values.resources.request.cpu }}
                  memory: {{ .Values.resources.request.memory }}
              command:
                - npm
                - start
              env:
              {{- with .Values.stressTester.env }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
          restartPolicy: OnFailure
{{- end -}}