apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deploy
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        name: {{ .Values.app.name }}-pod
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: "{{ .Values.app.name }}"
          image: "{{ .Values.be.image.repository }}:{{ default (include "app-demo.defaultTag" .) .Values.global.image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.resources.request.cpu }}
              memory: {{ .Values.resources.request.memory }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
          {{- with .Values.be.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.be.envFrom }}
          envFrom:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          
