{{- if .Values.autoscaling.horizontal.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}-deploy
  minReplicas: {{ .Values.autoscaling.horizontal.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.horizontal.maxReplicas }}
  metrics:
    {{- with .Values.autoscaling.horizontal.metrics }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}