apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ops-altronstudio-com-wildcard-certificate
  namespace: cert-manager
spec:
  secretName: ops-altronstudio-com-wildcard-cert-tls
  issuerRef:
    name: letsencrypt-prod-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - "[SUBDOMAINS COVERED BY CERTIFICATE]" ## Wildcard is allowed eg: *.hwcops.altronstudio.com
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "cert-manager-tls=ops-wildcard" ## Kubed annotation to sync on all namespace with this values