apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cloudflare
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: [email of domain owner]
    privateKeySecretRef:
      name: letsencrypt-prod-private-key-cloudflare
    solvers:
    - dns01:
        cloudflare:
          email: [email of domain owner]
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token