nameOverride: ""
fullnameOverride: ""

infisical:
  enabled: true
  name: infisical
  autoDatabaseSchemaMigration: true
  fullnameOverride: ""
  podAnnotations: {}
  deploymentAnnotations: {}
  replicaCount: 2

  image:
    repository: infisical/infisical
    tag: "v0.46.5-postgres"
    pullPolicy: IfNotPresent

  affinity: {}
  kubeSecretRef: "infisical-secrets"
  service:
    annotations: {}
    type: ClusterIP
    nodePort: ""

  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 350m

ingress:
  enabled: true
  hostName: "infisical.ops.altronstudio.com"
  ingressClassName: nginx
  nginx:
    enabled: false
  annotations: {}
  tls:
    - secretName: ops-altronstudio-com-wildcard-cert-tls
      hosts:
        - infisical.ops.altronstudio.com

postgresql:
  enabled: true
  name: "postgresql"
  fullnameOverride: "postgresql"
  auth:
    username: infisical
    password: root
    database: infisicalDB

redis:
  enabled: true
  name: "redis"
  fullnameOverride: "redis"
  cluster:
    enabled: false
  usePassword: true
  auth:
    password: "mysecretpassword"
  architecture: standalone