be:
  image: harbor.hwcops.altronstudio.com/latest/demo/be
  env:
    - name: PORT
      value: 3000
    - name: MIN
      value: 35
    - name: MAX
      value: 50

  envFrom: []

stressTester:
  image: harbor.hwcops.altronstudio.com/latest/demo/stress-tester
  env:
    - name: BE_ENDPOINT
      value: "be.prod.altronstudio.com"
    - name: NUM_TESTS
      value: 50

autoscaling:
  horizontal:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    averageRelativeCPU: 85
    averageRelativeMemory: 85

cronjob:
  enabled: false

domain:
  host: be.prod.altronstudio.com
  sslSecret: prod-altronstudio-com-wildcard-cert-tls