be:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 150Mi
  image:
    repository: harbor.hwcops.altronstudio.com/latest/demo/be
  env:
    - name: PORT
      value: "3000"
    - name: MIN
      value: "35"
    - name: MAX
      value: "50"

  envFrom: []

stressTester:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 150Mi
  image:
    repository: harbor.hwcops.altronstudio.com/latest/demo/stress-tester
  env:
    - name: BE_ENDPOINT
      value: "be.dev.altronstudio.com"
    - name: NUM_TESTS
      value: "50"

autoscaling:
  horizontal:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85

cronjob:
  enabled: true


ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, authorization"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, PATCH, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  domain:
    host: be.dev.altronstudio.com
    sslSecret: dev-altronstudio-com-wildcard-cert-tls
