be:
  env:
    - name: PORT
      value: 3000
    - name: MIN
      value: 35
    - name: MAX
      value: 50

  envFrom: []

autoscaling:
  horizontal:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    averageRelativeCPU: 85
    averageRelativeMemory: 85

domain:
  host: be.prod.altronstudio.com
  sslSecret: uat-bluontoolbox-com-wildcard-cert-tls